run:
	python cli.py --filepath data/orders_nested.json --history data/product_history.csv

test:
	pytest tests/

export:
	mkdir -p reports && python cli.py --filepath data/orders_nested.json --history data/product_history.csv